# Generated by Django 2.2.13 on 2020-11-04 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitrineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('linkedin', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('curso', models.CharField(choices=[('0', 'Sistemas para Internet'), ('1', 'Gestão Empresarial')], default='0', max_length=2, verbose_name='Curso Matriculado')),
                ('tipo_vaga', models.CharField(choices=[('0', 'Emprego'), ('1', 'Estágio'), ('2', 'Emprego ou Estágio')], default='2', max_length=2, verbose_name='Tipo da Vaga')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
