# Generated by Django 2.2.13 on 2020-07-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200609_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trainee_coordinator',
            field=models.BooleanField(default=False, verbose_name='Coodenador de Estágio'),
        ),
    ]
