# Generated by Django 2.2.13 on 2020-11-04 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_trainee_coordinator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'email'), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
