# Generated by Django 2.2.13 on 2020-06-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conveniomodel',
            options={'verbose_name': 'Convênio de Estágio', 'verbose_name_plural': 'Convênios de Estágio'},
        ),
        migrations.AddField(
            model_name='conveniomodel',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conveniomodel',
            name='documento',
            field=models.FileField(upload_to='convenios_estagio/'),
        ),
        migrations.AlterField(
            model_name='conveniomodel',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conveniomodel',
            name='observacao_professor',
            field=models.TextField(blank=True, default=''),
        ),
    ]
